export const UPLOAD = 'UPLOAD';
export const SELECT = 'SELECT';
export const PROCESS = 'PROCESS';
export const ACTIONS = {
  UPLOAD_PENDING: `${UPLOAD}_PENDING`,
  UPLOAD_FULLFILLED: `${UPLOAD}_FULLFILLED`,
  UPLOAD_REJECTED: `${UPLOAD}_REJECTED`,

  PROCESS_PENDING: `${PROCESS}_PENDING`,
  PROCESS_FULLFILLED: `${PROCESS}_FULLFILLED`,
  PROCESS_REJECTED: `${PROCESS}_REJECTED`,
};
